### ISSUE TITLE
Getting a wrong private-key type error when signing a bundle inside a react file and inside a component 

### ISSUE THREAD

**Issue by atob1** [Bundlr-Network/arbundles#13]
This code is causing the above error to be thrown despite the private key being correct.
![image](https://user-images.githubusercontent.com/57077728/141658591-c181e966-e3ac-440d-99fb-83b52adba9bf.png)

**Comment by joshbenaron** [comment]
This issue was fixed with the latest release. Migrating signing to `ArweaveSigner`
