### ISSUE TITLE
bundleAndSignData time complexity

### ISSUE THREAD

**Issue by 0xCryptoSheik** [Bundlr-Network/arbundles#15]
Hi,

While testing bundling of several hundreds data items, I've noticed that `bundleAndSignData` could make the Node.js process OOM, or take a very long time - increasing non-linearly.

The issue seems to be caused by the way the data items buffers are concatenated into the final bundle buffer, indeed [this is how it's done at the moment](https://github.com/Bundlr-Network/arbundles/blob/64b4032b57c16277fbed26d8c65880410bdb0e39/src/ar-data-bundle.ts#L56):

```js
    return a.reduce((previousValue, currentValue) => {
      return Buffer.concat([previousValue, currentValue]);
    }, Buffer.allocUnsafe(0));
```

Blocks https://github.com/metaplex-foundation/metaplex/pull/859

Technical storytelling: https://twitter.com/0xCryptoSheik/status/1461634813706883076?s=20

**Comment by joshbenaron** [comment]
Yep, memory allocation isn't O(n) so as the bundle grows it will get slower non-linearly. I have planned to reimplement it to use non-contiguous memory. So `Bundle` would just be a wrapper for `Array<DataItem>` (with some added logic).

We also have an undocumented file API at `arbundles/file`. It's labelled as unstable at the moment. This doesn't have the same memory limits as the in-memory API.

Can I ask why you're integrating bundles directly into Metaplex? - my understanding is you upload single data items and then the data is guaranteed to seed.

**Comment by 0xCryptoSheik** [comment]
Hi,
Thanks for your response :)

Please forgive me if I’m wrong, not an expert, but wouldn’t my fix or
something along those lines be sufficient for making memory allocation O(n)
?

I’m a bit busy doing other things right now, and I couldn’t test as much as
I wanted to.

Also please allow me to come back to you a bit later for the context around
the integration in Metaplex Candy Machine CLI.

Thanks for your consideration.

**Comment by joshbenaron** [comment]
I meant in general allocating contiguous memory isn't O(n) for large chunks of memory.

Does the PR improve overall performance?

**Comment by 0xCryptoSheik** [comment]
I don't think re-implementing using non-contiguous memory is necessary in regard to this issue, the PR I've provided appears to work fine according to my tests.

I would gladly use the File API once it's stable, since it's tricky (though possible) for the Metaplex Candy Machine CLI use case to split files > 250 MB, but it is a rare case anyway.

As part of Metaplex's tooling, there's the "Candy Machine CLI" which allows to create collections of NFTs, right now the default Arweave upload method is leveraging a closed-source serverless function maintained by Metaplex, for which users pay a fee in SOL & only handles a single asset file pair (usually PNG + JSON) at a time.
This is described by users as a slow, clunky, expensive & obscure mechanism, though it is the most accessible.

By implementing native Arweave Bundles upload inside Metaplex Candy Machine CLI, we allow users to mass upload to Arweave directly using their own AR wallet, benefiting from all the arbundles goodness.

> I meant in general allocating contiguous memory isn't O(n) for large chunks of memory.

Yeah, I figured that's what you meant, I really don't know about that, but I believe the previous way of concatenating Buffers itself was O(n^2), with my PR it's now O(n), do you concur?

> Does the PR improve overall performance?

Yes, this PR drastically improves overall performance:

### Before 

> Bundled 2640 data items in 192.749s (880 assets, 30MB)

https://twitter.com/0xCryptoSheik/status/1461643308988575747

### After

> Bundled 2640 data items in 9.5s (880 assets, 30MB)

https://twitter.com/0xCryptoSheik/status/1461717558151847942

**Comment by joshbenaron** [comment]
Wow. Huge improvement. Thanks for the PR!

Re bundles - sure I get that. There are actually some complexities to going direct to Arweave which is why Metaplex don't support it right now. 
Metaplex uses Bundlr to upload to Arweave (inside the GCP function) which is a scaling network for Arweave but also provides a way better UX. It allows for payment in any crypto. We've just added support for MATIC and soon we're going to support SOL, so the plan was they could reimplement the server-side Metaplex code all client side and pay in SOL.

Btw - here's the [discord](https://discord.com/invite/Z4YQwAbQMP). Might be easier to talk there

**Comment by joshbenaron** [comment]
Closing as time complexity issue solved with previous PR. Thanks @0xCryptoSheik
